version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: helpdesk-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helpdesk_local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - helpdesk-network

  # pgAdmin - Database GUI (Opsiyonel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: helpdesk-pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - helpdesk-network

  redis:
    image: redis:8-alpine
    container_name: helpdesk-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass helpdeskSecretPass
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - helpdesk-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: helpdesk-redisinsight
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/data
    networks:
      - helpdesk-network

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  redisinsight_data:

networks:
  helpdesk-network:
    driver: bridge
