version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: helpdesk-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass helpdeskSecretPass
    volumes:
      - redis_data:/data

volumes:
  redis_data:
